### ISSUE TITLE
2dx_image: map dimensions of symmetrized map

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#124]
When working with a map of unit cell size 122A, 71A, 90deg, with symmetry p2221b, then the final map has unit cell dimensions of 122A x 71A x 250A in p1 (i.e., displayed correctly as 122 x 71 image), but has unit cell dimensions of 71A x 250A x 122A in p2221b (i.e., is displayed as 71 x 250 image, which is wrong). 
"p2221b" sets "rotate_to_Z" to "yes", which might cause the problem in 2dx_generateMap_sub.com with CCP4 routines.  We should replace that with Nikhil's new map generation routines.

**Comment by sthennin** [comment]
Basis Vectors XYZ go to ZXY, and Cell Axes lengths are permutated.

**Comment by nikhilbiyani** [comment]
This is already done, if not reopen please!
