### ISSUE TITLE
Project Library: New functions: What is "Second Project"?

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#128]
- When trying to move selected directories to a second project, it sais in the console "Error in copying images! Second project not set!", but I don't know how or where to set that second project location. 

Otherwise, this is a great set of very useful new functions.

Tried on OS X, 10.11.1 on Dec. 6, 2015.

**Comment by sthennin** [comment]
Now I get it:  "Selected" means the highlighted image directory, not the one that is "checked".  Ok, the first point is then functional.  However, it might be better to speak about "highlighted" image directories, and not "selected".

**Comment by nikhilbiyani** [comment]
I just improved the message. 

The second project can be used to prepare another 2dx project and transfer (copy and not move) images from current project. 

@sthennin : This functionality is from past! Do we need it?

**Comment by sthennin** [comment]
Yes, the functionality is very useful, if there are two conformations in the dataset. With this function, one can easily move an image to a different conformation. Actually, most of the projected have this problem.
However, in the current function I have a problem with "Copy to second project" vs. "Move to second project".  What we would need is to "Move" an image to a second project directory. We will never need "Copy". Copy is only rarely needed and could rather be done manually in the file system. Move is what we need in practice.

**Comment by nikhilbiyani** [comment]
Okay. So then we can provide two functionalities. One to move to a different folder (we can call it as sets) and other one to move to different project.  Moving to a different project will allow users to create two maps.

**Comment by nikhilbiyani** [comment]
@sthennin : Should I change the "Copy" function to "Move" for second project!
