### ISSUE TITLE
normalize_TANGL.py (in merge  3D iterative) needs a new solution

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#154]
This still deals with individual 2dx_image.cfg files.

**Comment by nikhilbiyani** [comment]
The parameters can be changed via the results file, as we do in CSH files. For saving while the script is still running, (like in the iterative ones), we can introduce some take like <<evaluate>>, (e.g.. <<saveresults>> which can save the results file to cfg files.

**Comment by nikhilbiyani** [comment]
Now <<evaluate>> saves the results as well.

**Comment by nikhilbiyani** [comment]
Implemented
