### ISSUE TITLE
Single Particle functions in FullScreenBrowser

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#160]
Wishlist:
GAUTOMATCH requires as input parameter an expected particle diameter (gautomatch_diameter) and a CrossCorrelation Cutoff value (gautomatch_cc_cutoff).
GAUTOMATCH produces a band-pass filtered version of the image ${movie_stackname}_bgfree.mrc, which is now displayed in the GUI of FOCUS also. 
GAUTOMATCH also produces a STAR file ${movie_stackname}_automatch.star with the X/Y coordinates and the CCvalue of identified particles. 

When double-clicking on the band-pass filtered image (or the original image), the full-screen browser should be able to display the identified particle positions from that STAR file with circles that have the diameter that was specified as input parameter for FOCUS. The color of the circles could be a function of the CC value of that particle. This would ideally be available upon pressing "p".

**Comment by nikhilbiyani** [comment]
Implemented
