### ISSUE TITLE
FOCUS doesn't compile on OS X right now, with a library issue (threads)

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#161]
[ 19%] Linking Fortran executable 2dx_fftrans.exe
Undefined symbols for architecture x86_64:
  "_fftwf_init_threads", referenced from:
      _tdxfft_ in libfft.a(fftlib.cpp.o)
  "_fftwf_plan_with_nthreads", referenced from:
      _tdxfft_ in libfft.a(fftlib.cpp.o)
  "_fftwf_cleanup_threads", referenced from:
      _tdxfft_ in libfft.a(fftlib.cpp.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [kernel/mrc/source/2dx_fftrans.exe] Error 1
make[1]: *** [kernel/mrc/source/CMakeFiles/2dx_fftrans.dir/all] Error 2
make: *** [all] Error 2
Build failed for Focus

**Comment by nikhilbiyani** [comment]
It complies, on my macOS, you would need to install the fftw threaded library. Try:

brew install fftw

**Comment by nikhilbiyani** [comment]
It was probably mixed up FFTW libraries.
