### ISSUE TITLE
Uneven dimensions in FFT in FullScreenBrowser

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#162]
The full-screen browser should be able to deal with non-square images:
When an image of 4000 x 3000 px is Fourier transformed, the FFT has dimensions of
2001 x 3000 pixels (only X>=0 part is in file). The display then is 4001 x 3000 pixels.
Nevertheless, the last pixel on the top and on the right edge is Nyqvist, which is 1/(2 px) resolution. 
This FFT should nevertheless be displayed as square thing, with round Thon rings.

**Comment by nikhilbiyani** [comment]
Fixed now.
