### ISSUE TITLE
Script during import: Result parameters are not evaluated

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#165]
An import script runs now, but the results are not read into the database.

Also: It was not easy to make the import script accessible in the Process panel. I did that with a symlink but that is a hack.

**Comment by sthennin** [comment]
... and: "After Import" jobs are not fed into the batch queue (?).   Example runs on Polara with Thorsten downstairs.

**Comment by nikhilbiyani** [comment]
Fixed now
