### ISSUE TITLE
Defining memory limit for wiping

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#166]
Settings -> System -> Limit to initiate wiping of fast SCRATCH [MB]
for some reason, I can only enter "0" or multiple "000", but not a "1" or other digit... ?
Is this because of the range limit
\# TYPE: Integer "MIN=100;MAX=10000000000;DEFAULT=50000"

**Comment by nikhilbiyani** [comment]
This parameter does not exist anymore.
