### ISSUE TITLE
Sourcing csh files with arguments on some platform does not work

### ISSUE THREAD

**Issue by nikhilbiyani** [C-CINA/focus#171]
On some platforms sourcing CSH files with arguments does not work. In these cases, the arguments have to be left out from the sourcing command and have to added to a variable argv before the sourcing command.

`source ${proc_2dx}/a_script.com arg1 arg2`

should be changed to

```
set argv=( "arg1" "arg2" )
source ${proc_2dx}/a_script.com
```

**Comment by nikhilbiyani** [comment]
This might also be when csh is different than tcsh on platforms. We should replace csh with tcsh.

**Comment by PaulVanSchayck** [comment]
I can confirm that with csh-bsd this is indeed a problem. On many debian/ubuntu install I suspect that /bin/csh is set to /bin/bsd-csh and not tcsh. 

Fixing this on debian/ubuntu can be done with
```
sudo update-alternatives --set csh /bin/tcsh
```

But maybe it's better if this is fixed in the focus scripts.

**Comment by n1kt0** [comment]
that worked on Ubuntu 17.10. thx @PaulVanSchayck for the workaround.

**Comment by rdrighetto** [comment]
Hi,

We don't have to change csh to tcsh, which is better and safer. In modern Linux distros csh is just a link to tcsh. I updated the documentation to make it clearer:
https://focus.c-cina.unibas.ch/wiki/doku.php?id=1_0:external-tools#t_csh

**Comment by rdrighetto** [comment]
Thanks for your tip, Paul. Agree having a check would be good.
Speaking for myself, I was surprised to find out that the "old school" csh is still lying around - I thought nowadays it was always tcsh disguised as csh.
