### ISSUE TITLE
Double click group in library crashes Focus

### ISSUE THREAD

**Issue by PaulVanSchayck** [C-CINA/focus#179]
When I double click a group in the library view of focus I will get a segfault of the program. Double clicking on an image will open the processing tab as expected.

I have no back trace, only this:
```
[7010318.696230] focus[3329]: segfault at 18 ip 000000000054c0a0 sp 00007fff5f7b99c8 error 4 in focus[400000+237000]
```

This is on Ubuntu 14.04, with Qt 5.2.1 and self compiled version of the git version of Focus of today.

**Comment by nikhilbiyani** [comment]
Reproducible! Needs a fix soon.
