### ISSUE TITLE
Status page shows always 111 images processed during last hour

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#182]
... also, if the last activity of the processor was 4 days ago.
Also, the number of images processed varies, between 96 and 120.

**Comment by nikhilbiyani** [comment]
This is possible when some scripts are run in focus using parallel batch-queue processor, even after importing. These processing will also show up in the status-webpage. We can change this behaviour to only import!

**Comment by sthennin** [comment]
True. This was not a bug, the system was simply still re-processing all images. Raphi set it to do so.
