### ISSUE TITLE
Pixel size for TomoAlign script does not reflect the changes for the new default for 8k images

### ISSUE THREAD

**Issue by thklose** [C-CINA/focus#191]
The changes in scripts/image/align/import_driftcor_motioncor2.script are not reflected in scripts/image/tomoalign/tomo_driftcor_motioncor2.script yet, which results in a wrong pixel size for the MotionCor2 input and an error when motioncor2_plotter.py is called without the pixel size parameter.

**Comment by sthennin** [comment]
Should be fixed now.
