### ISSUE TITLE
No FFT of image in 2D crystal mode

### ISSUE THREAD

**Issue by albertlibra** [C-CINA/focus#193]
Hi-
I am using focus 1.1.0, 2D crystal mode.In 2dx_image, after "init files and parameters",I ran "calculate FFTs". But no FFT outputs.
Terminal showed **"Source of spots contains no option "FFT of image"**
And log file in 2dx_GUI showed
_**### _#################################2dx_fftrans##################################
==== app_python = /usr/bin/python2.7 ==================================================================================
==== Sourcing 2dx_init_files_sub.com ==================================================================================
==== Testing if 2000000000000000.mrc exists ===========================================================================
==== 2000000000000000.mrc exists (1) ==================================================================================
==== Testing Endianess. ===============================================================================================
==== Endedness is correct. ============================================================================================
==== Testing correct size of input image. =============================================================================
==== correcting domask to y ===========================================================================================
==== Verifying some parameters ========================================================================================
==== Calculating pixel size on sample level as 2.5 Angstroems. ========================================================
==== Sourcing 2dx_fftrans_sub.com =====================================================================================
==== Calculate FFT from 2000000000000000 ==============================================================================
==== HISTO - to produce a histogram of the grey-values in the image ===================================================
==== TAPEREDGE: To taper the edges to prevent stripes in the FFT ======================================================
==== FFTRANS - to calculate Fourier transform of image ================================================================
############################2dx_fftrans finished.#############################_**_

**Comment by sthennin** [comment]
Hi,
to trace this better to the source, could you provide the full verbosity output of that Output Window, please?
(From above: Your filename 2000000000000000.mrc is really long. Did you try with a shorter filename? What is your image number that you use here? The underlying MRC software only allows 10 digits for image numbers. 

I am puzzled by your statement about "No Option FFT of Image". That looks like you are applying FOCUS to an old dataset where you used 2dx before?  The parameter "spot_source" now has settings of "0", "1", "2", etc., not any more that text. That text was in the older version of scripts. Could this be? In that case, you could simply set the parameter to a new value and after saving the parameters (they are autosaved now) that error message should go away. 

Henning
