### ISSUE TITLE
Import .tif files

### ISSUE THREAD

**Issue by 2dimensionalcharacter** [C-CINA/focus#200]
I'm not sure if this is the right place to ask this, but is there any way to get focus to import .tif files instead of stacks? The EM I'm using does not generate stacks.

**Comment by rdrighetto** [comment]
Unfortunately, at the moment FOCUS cannot import single .tif files,
however, it can import single .mrc files.
We'll work on supporting .tif images directly, but in the meanwhile, I
advise you to convert your .tif images to .mrc (for example, using
e2proc2d.py from EMAN2.2, or em2em) before importing into FOCUS.


--
Ricardo Diogo Righetto

2017-09-01 3:09 GMT+02:00 2dimensionalcharacter <notifications@github.com>:

**Comment by sthennin** [comment]
We now added a script to import *.tif or *.tiff files. Please give it a try.
Henning.
