### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by rajanprabu** [C-CINA/focus#210]
Hi, 
This is not a scientific question but an installation issue, probably due to my ignorance. My apologies first.

We would like to have our remote monitoring running. I have setup the apache, php and webdav on my server and everything seems to be working. But when i go to my server http://blabla.de/ I dont see the login page, but it straight takes me to the status page. But even the status page is  empty ( I can see the backbone of the page but fields are empty even thumbnails no logs etc). I have checked that the caldaver can push the files and they are right there. Please let me know what I am missing here. 

Thanks for your time and effort. I have attached a screenshot below

best
Rajan

![screenshot at 2018-01-25 12 11 04](https://user-images.githubusercontent.com/29671655/35386074-f02997de-01ca-11e8-9fff-064f61cb94c4.png)

**Comment by rajanprabu** [comment]
I just made a soft link from webdav to the webserver directory and it worked just fine.. Thanks

**Comment by rdrighetto** [comment]
Thanks for sharing the solution you found. Please don't hesitate to contact us if you need help again.
