### ISSUE TITLE
Tutorial data download (2D crystal)

### ISSUE THREAD

**Issue by weifeng8322** [C-CINA/focus#213]
Dear all, 
Dose any one know how to download the test data about 2D CRYSTAL used in the tutorial  movie (https://youtu.be/zITHQT1OCUA)
Thank you for your help!
Wei

**Comment by sthennin** [comment]
Hi,
I just uploaded those images to
https://focus.c-cina.unibas.ch/wiki/doku.php?id=1_0:2dx_test_data

All the best,

Henning.

Henning Stahlberg, PhD
Prof. for Structural Biology, C-CINA, Biozentrum, University Basel
Mattenstrasse 26 | D-BSSE | WRO-1058 | CH-4058 Basel | Switzerland
http://c-cina.org | Tel. +41-61-387 32 62



On 5 Mar 2018, at 14:24, weifeng8322 <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear all,
Dose any one know how to download the test data about 2D CRYSTAL used in the tutorial movie (https://youtu.be/zITHQT1OCUA)
Thank you for your help!
Wei

**Comment by weifeng8322** [comment]
Got it, Thank you very much for your help!
