### ISSUE TITLE
Deal with the thin crystal as 2d crystal?

### ISSUE THREAD

**Issue by weifeng8322** [C-CINA/focus#214]
Dear all,
I have a crystal about 100nm thick，can I use electron tomography method to collect a series of  project, and then  process these projects just as 2d crystal does?
The cell parameter of the crystal is (P1, 100,100,100,90,90,90)
Thank you for your time!
Wei.

**Comment by weifeng8322** [comment]
The cell parameter of the crystal is (P1, 100Å,100Å,100Å,90°,90°,90°)

**Comment by rdrighetto** [comment]
Hi @weifeng8322,

Interesting question. I think these crystals are too thick to be treated as
2D crystals. However it sounds to me a perfect case for collecting electron
diffraction data ("MicroED"/"NanoED"). The technique is pretty much
analogous to macromolecular X-ray crystallography, but using a TEM.

Here are two references on the technique:

http://scripts.iucr.org/cgi-bin/paper?S2053273315010669
http://scripts.iucr.org/cgi-bin/paper?S2053273315022500

If you are interested in further discussing these methods please contact us
by e-mail.

Best wishes,



--
Ricardo Diogo Righetto

2018-03-13 16:04 GMT+01:00 weifeng8322 <notifications@github.com>:
