### ISSUE TITLE
Beginner user a bit lost...

### ISSUE THREAD

**Issue by acdrennan** [C-CINA/focus#217]
Hello,
I am learning to use 2dx.

In SBGrid, I open 2dx_merge and select my folder (on the desktop) to tell the program where I want the files to go.

On the GUI, I filled in in some parameters for a typical negative stain project: RESMIN 200 A, RESMAX 16 A. Save.

File --> Import Images --> select TIFF image (on desktop (not in file defined above)). (I am just trying to load one file). Fill in the name, angle, number, and sub-image for this file, and the program automatically gives it a new name according to the naming conventions: First 4 letters: protein name; next 2 digits: tilt angle (here 00); next 6 digits: image number; next 2 digits: subframe. (see attached image "merge".)
![merge](https://user-images.githubusercontent.com/38112302/38383058-15c581a0-38d1-11e8-89e3-14ca46971e8d.jpeg)

Double-click on the lite entry of this image in the central top panel of 2dx_merge to open 2dx_image with this image. (see attached image "imageinit".) (Note that I changed the image number, name, and non-masked image name here.)
![imageinit](https://user-images.githubusercontent.com/38112302/38383158-5aa53f9a-38d1-11e8-8acb-05bb383a1bf8.jpeg)

Then when I try to run programs, it says "image not found"; for example:
#################################2dx_fftrans##################################
==== Verifying some parameters =======================================================================================
==== Creating MRC format file. =======================================================================================
==== Image Sp42.mrc does not exist. ==================================================================================
==== Neither image Sp42.tif nor Sp42.raw.mrc do exist. ===============================================================
==== Image Sp420000000101.tif found...converting (2). ================================================================
############################2dx_fftrans finished.#############################
dyld: Library not loaded: @executable_path/../lib/libfftw3f.3.dylib 
Referenced from: /Volumes/SBGrid/i386-mac/2dx/3.4.2/2dx_image/bin//tif2mrc.exe 
Reason: image not found 

What am I missing here? Is there a better way to do this? I have used the book "Electron crystallography of soluble and membrane proteins" to get this far, but some of it is outdated; is there a better resource?

Thank you for your time.

**Comment by sthennin** [comment]
Hi,
2dx is outdated, and not supported any longer.
Please use FOCUS. We strongly recommend to install FOCUS from source, not from SBGrid, where you might have an outdated version.

FOCUS includes everything that 2dx can, and more.
http://focus-em.org

An example is described at
https://focus.c-cina.unibas.ch/wiki/doku.php
Or directly here:
https://www.youtube.com/watch?v=zITHQT1OCUA&feature=youtu.be

All the best,

Henning.

Henning Stahlberg, PhD
Prof. for Structural Biology, C-CINA, Biozentrum, University Basel
Mattenstrasse 26 | D-BSSE | WRO-1058 | CH-4058 Basel | Switzerland
http://c-cina.org | Tel. +41-61-387 32 62



On Apr 5, 2018, at 8:06 PM, acdrennan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I am learning to use 2dx.

In SBGrid, I open 2dx_merge and select my folder (on the desktop) to tell the program where I want the files to go.

On the GUI, I filled in in some parameters for a typical negative stain project: RESMIN 200 A, RESMAX 16 A. Save.

File --> Import Images --> select TIFF image (on desktop (not in file defined above)). (I am just trying to load one file). Fill in the name, angle, number, and sub-image for this file, and the program automatically gives it a new name according to the naming conventions: First 4 letters: protein name; next 2 digits: tilt angle (here 00); next 6 digits: image number; next 2 digits: subframe. (see attached image "merge".)
[merge]<https://user-images.githubusercontent.com/38112302/38383058-15c581a0-38d1-11e8-89e3-14ca46971e8d.jpeg>

Double-click on the lite entry of this image in the central top panel of 2dx_merge to open 2dx_image with this image. (see attached image "imageinit".) (Note that I changed the image number, name, and non-masked image name here.)
[imageinit]<https://user-images.githubusercontent.com/38112302/38383158-5aa53f9a-38d1-11e8-8acb-05bb383a1bf8.jpeg>

Then when I try to run programs, it says "image not found"; for example:
#################################2dx_fftrans##################################
==== Verifying some parameters =======================================================================================
==== Creating MRC format file. =======================================================================================
==== Image Sp42.mrc does not exist. ==================================================================================
==== Neither image Sp42.tif nor Sp42.raw.mrc do exist. ===============================================================
==== Image Sp420000000101.tif found...converting (2). ================================================================
############################2dx_fftrans finished.#############################
dyld: Library not loaded: @executable_path/../lib/libfftw3f.3.dylib
Referenced from: /Volumes/SBGrid/i386-mac/2dx/3.4.2/2dx_image/bin//tif2mrc.exe
Reason: image not found

What am I missing here? Is there a better way to do this? I have used the book "Electron crystallography of soluble and membrane proteins" to get this far, but some of it is outdated; is there a better resource?

Thank you for your time.

**Comment by acdrennan** [comment]
Ok, thanks!

**Comment by sthennin** [comment]
Please update to the newest version of FOCUS. This should be working now also on OSX.
