### ISSUE TITLE
2D crystal image analysis on preliminary negative stain images?

### ISSUE THREAD

**Issue by acdrennan** [C-CINA/focus#219]
I am attempting to use FOCUS to analyze preliminary negative stain 2D crystals. I know FOCUS is built to analyze cryo images... can it be used for negative stain images as well?

I've been using the YouTube video "FOCUS 2D crystals 1" to help me navigate the program, and although I can import my .tif images, it seems that perhaps they are recognized as a stack. The reason I think this is that when I double-click on an imported image, there is no "import 2D image" folder under the "process" tab; instead, there is an "unpack stack" folder. 

Note also that in the video, the 2D images are described as "2D image", while mine are described as "Average". I am using a CCD camera.

If focus will not support my analysis, is there a another program that might work?

**Comment by sthennin** [comment]
Yes, for neg. stain, you simply have to invert the contrast when creating the final map. Everything else stays the same.

Did you run FOCUS in the "2D Electron Crystallography" mode? If not, you can change the mode if you click top left onto the "Project" button, and then click on the second button top left in that window, labeled "Change Project Mode". Depending on the project mode, different scripts will appear. If you are in single particle mode, then some of the scripts are different.
The Prepare scripts should be called 
- Import Movie from SerialEM
- Import Movie from Digital Micrograph
- Import Movie from EPU
- Import 2D Image

If you have different scripts there, then which version do you run? It might be outdated? Where did you get FOCUS from? 

Import should be with the script “Import 2D Image” from the “Prepare" section. 
Then you could continue with the “2DXtal” section scripts.

**Comment by acdrennan** [comment]
I did run FOCUS in the 2D Electron Crystallography Mode. I am running Focus 1.1.0, and I believe it is set up to update every evening. I got focus from SBGrid, as my IT department will not allow me to run it from the source.

**Comment by sthennin** [comment]
SBGrid updates from our nightly builds regularly. Which version do you use, OSX or Linux? If you call the "About" (Linux) or "About focus" (OSX) panel, which revision number do you see?  Is that 37778f87?

Does it look like this? 

<img width="1181" alt="screen shot 2018-04-17 at 14 00 48" src="https://user-images.githubusercontent.com/6606048/38868584-d0547466-4247-11e8-81e7-cf3f80d010e4.png">

**Comment by acdrennan** [comment]
I use OS X.

Actually, now I cannot get past the project initialization page, so am unable to check the "About Focus". I get this error in the terminal:
/programs/i386-mac/focus/1.1.0_nightly/bin/focus: line 6: 20400 Segmentation fault: 11  ${binDir}/../focus/focus.app/Contents/MacOS/focus $*

**Comment by sthennin** [comment]
Dear Amanda, 
I understand that you work on a Mac with OSX, but have SBGRID install the software onto your Mac?  SBGRID is probably downloading our pre-compiled binaries from https://focus.c-cina.unibas.ch/download.php and pushing them onto your Mac in the background. We have three different OSX versions, for OS 10.10, 10.11, and 10.12. Are you sure that SBGRID is pushing the correct version to your computer? 
On my Mac, the correct version works.

**Comment by acdrennan** [comment]
I was able to get the correct version to run on my mac when I downloaded the version that is updated nightly (but _not_ the stable version, and not via SBGrid). In my ignorance I did not realize that I need to have a graphics card... so I am stuck here for now. 
Many thanks for all of your help.

**Comment by sthennin** [comment]
Hi,
For 2D crystal analsysis,you don’t need a GPU.
Only MotionCor2, gCTF, and gAutomatch need the NVIDIA GPU.
FOCUS itself uses any GPU that is in the computer, including OS X.

Henning.

Henning Stahlberg, PhD
Prof. for Structural Biology, C-CINA, Biozentrum, University Basel
Mattenstrasse 26 | D-BSSE | WRO-1058 | CH-4058 Basel | Switzerland
http://c-cina.org | Tel. +41-61-387 32 62



On Apr 19, 2018, at 9:23 PM, acdrennan <notifications@github.com<mailto:notifications@github.com>> wrote:


I think my mac (OS 10.12.6) has an internal GPU, but it isn't made by NVIDIA, and CUDA only runs on NVIDIA cards...

**Comment by acdrennan** [comment]
Hi Henning, 
When I try to run the "Import 2D Image" script I get this output (see below). I am trying to get IT to install gawk for me today, hopefully that will fix the problem.

#################################import_image#################################
 
==== RELION installation directory not found. Is it installed ??? =====================================================================================================================================
==== /usr/local/relion ================================================================================================================================================================================
==== The location of RELION installation is defined in Preferences. ===================================================================================================================================
 
==== cuda library path /usr/local/cuda/lib64 is not a valid directory. ================================================================================================================================
############################import_image finished.############################
/usr/local/Cellar/gawk: Command not found.

**Comment by acdrennan** [comment]
Ok, I've got gawk installed, but now I am getting this error:
#################################import_image#################################
==== cuda library path /usr/local/cuda/lib64 is not a valid directory. ================================================================================================================================
==== Running: clip unpack image_2dx.tif image_2dx.mrc =================================================================================================================================================
############################import_image finished.############################
/Applications/IMOD/bin/clip: line 3: /bin/realbin/clip: No such file or directory

**Comment by rdrighetto** [comment]
Hi,

It is trying to run the program 'clip' from IMOD, but is not finding it.
Please install IMOD and tell FOCUS where it is located, by clicking on
"Preferences" >> "Software" tab.
The full list of external program dependencies is available on the Focus
Wiki:
https://focus.c-cina.unibas.ch/wiki/doku.php?id=1_0:external-tools

Best wishes,


--
Ricardo Diogo Righetto

2018-04-20 22:58 GMT+02:00 acdrennan <notifications@github.com>:

**Comment by sthennin** [comment]
Hi,
We also added some changes to scripts in FOCUS, and updated the third-party software installation manual pages on https://focus.c-cina.unibas.ch/wiki/doku.php?id=1_0:external-tools specifically for OSX. Please give it a try now, after updating to the newest version. Thanks.

**Comment by acdrennan** [comment]
Yes, I have it working this morning. I am trying to work out some strange FFTs but I am happy that it is up and running. Thank you!
