### ISSUE TITLE
Keyboard input fails on browse file entries

### ISSUE THREAD

**Issue by cherre** [C-CINA/focus#220]
Using 1.1.0 - nightly build both Mac and Linux(RPM) 

   I can't seem to get any fields that are associated with a file browse to allow keyboard input.  The problem occurs in the compiled binaries available for download and when code it built from source.  The QT and fftw was obtained following instructions in  INSTALL.SOURCE

The text fields without associated "browse" button accept Keyboard input

**Comment by sthennin** [comment]
That is normal behavior. Please click on the file icon and navigate to the file.

Henning Stahlberg
HStahlberg@me.com<mailto:HStahlberg@me.com>
http://c-cina.org
Tel.: +41-79-502 75 22
(sent from iPhone)

On May 11, 2018, at 20:40, cherre <notifications@github.com<mailto:notifications@github.com>> wrote:


Using 1.1.0 - nightly build both Mac and Linux(RPM)

I can't seem to get any fields that are associated with a file browse to allow keyboard input. The problem occurs in the compiled binaries available for download and when code it built from source. The QT and fftw was obtained following instructions in INSTALL.SOURCE

The text fields without associated "browse" button accept Keyboard input

**Comment by cherre** [comment]
Henning,

 thanks for the reply.   Is it also expected that "focus" won't accept data
from keyboard when using X11 forwarding?  Using ssh to access a remote
linux box, run focus displaying back to  mac.  Works great until attempting
to use the keyboard to enter data.  Is that expected??  I tried both "ssh
-Y" and "ssh -X".

thanks -- carol
