### ISSUE TITLE
EPU import is resulting in the same raw_gaincorrectedstack.mrcs file for all imported micrographs

### ISSUE THREAD

**Issue by PaulVanSchayck** [C-CINA/focus#228]
I'm using the latest git source from today. Build on Ubuntu 16.04 using stock packages.

When using the 'Import is from EPU' option the importer nicely finds all .mrc files in the */Data sub directories.  However when reviewing the images, they are all exactly the same.

And by the same, I really mean the same file. Confirmed by this output:
```
$ md5sum */raw_gaincorrectedstack.mrcs
3b079d2a7649fc7d312c9dc22cd4729a  0000000170/raw_gaincorrectedstack.mrcs
3b079d2a7649fc7d312c9dc22cd4729a  0000000171/raw_gaincorrectedstack.mrcs
3b079d2a7649fc7d312c9dc22cd4729a  0000000172/raw_gaincorrectedstack.mrcs
3b079d2a7649fc7d312c9dc22cd4729a  0000000173/raw_gaincorrectedstack.mrcs
3b079d2a7649fc7d312c9dc22cd4729a  0000000174/raw_gaincorrectedstack.mrcs
3b079d2a7649fc7d312c9dc22cd4729a  0000000175/raw_gaincorrectedstack.mrcs
```

This does not happen if I manually select a GridSquare directory and do not use the 'Import is from EPU' option.

Am I doing something wrong? Is this a bug?

**Comment by andreymalg** [comment]
I am also having the same problem.

**Comment by hansenbry** [comment]
I'm seeing this same issue using CentOs7.5.  Using the same workaround of putting all the .mrc and .xml in a single folder and not using the import as EPU data

**Comment by rdrighetto** [comment]
Apologies for the delay. We don't have a solution yet to this bug. I am looking into it. I understand that it still works with the workaround suggested by @PaulVanSchayck ?

**Comment by hansenbry** [comment]
Hi I tried a workaround of creating symlinks to the data in all the Gridsquare folders so it could be a single import instead of multiple, but focus doesn't see the symlinked files.  If I open the folder in a browser window I see "files" in there from the symlink. Is there something I can do to get focus to recognize symlinked data?

**Comment by rdrighetto** [comment]
Hi Bryan,

Indeed FOCUS does not recognize symlinks on import - this is on purpose to
ensure compatibility across different flavors of *nix systems.
I'm afraid the only workaround at the moment is to copy all your movies to
a single location and do "normal" i.e. non-EPU import. Perhaps you could
arrange a shell script to do this periodically, outside of FOCUS? Sorry for
the inconvenience.

The good news is that I already found the bug in the code, and am working
on a solution. I'll let you know when it is ready - hopefully still today.

Best wishes,

--
Ricardo Diogo Righetto


Em qui, 6 de set de 2018 às 21:52, Bryan Hansen <notifications@github.com>
escreveu:

**Comment by rdrighetto** [comment]
Should be fixed now. Please feel free to reopen this issue if the problem persists.

**Comment by PaulVanSchayck** [comment]
@rdrighetto Thanks for taking a look at this. I'll test it, and report back to you.
