### ISSUE TITLE
Request:Bayesian polishing in Relion3.0

### ISSUE THREAD

**Issue by Eladbic** [C-CINA/focus#231]
#The new version of Relion have the option of Bayesian polishing. To do it one need to run the motioncor within Relion because required metadata about the motion correction is  written out by the Relion-motioncor.
Can this metadata being written out?

**Comment by rdrighetto** [comment]
Hi,

Please send us an example of such metadata (I understand it is a new .star file) and we will look into implementing it. Another possibility would be to run Relion's MotionCor2 implementation from within FOCUS.

**Comment by Eladbic** [comment]
Hi,
Thanks for your help.
This is an example for the new .star file from Relion motioncor2 job:

 data_

loop_ 
_rlnMicrographName #1 
_rlnMicrographMetadata #2 
_rlnAccumMotionTotal #3 
_rlnAccumMotionEarly #4 
_rlnAccumMotionLate #5 
MotionCorr/job061/xenoA_2169.mrc MotionCorr/job061/xenoA_2169.star    15.637464     1.189596    14.447868 
MotionCorr/job061/xenoA_2168.mrc MotionCorr/job061/xenoA_2168.star    17.497252     0.852047    16.645206 

Best,

**Comment by rdrighetto** [comment]
FOCUS now exports the metadata from MotionCor2 in the format expected for Bayesian polishing in RELION-3. Commit 77edb1d14178ab44b594d1fdbbaf09e83fe17a25

**Comment by Eladbic** [comment]
Thanks for your help.
