### ISSUE TITLE
Minor problems with exported Micrographs_all_defocus.star

### ISSUE THREAD

**Issue by andreymalg** [C-CINA/focus#232]
Hello, 

Here are 2 small issues I've run into with the exported micrographs_all_defocus.star in Relion2. 
1) My installation of Relion 2.1 does not recognize "_rlnTotalDose" 
2) When trying to display CTFs in Relion, this error pops up: 
"Invalid  Spider file: ctfinfo/Imagename.ctf "

Both can be readily addressed with awk and vim.
1) Using awk to print out the first 13 columns
2) vim to change ctfinfo/Imagename.ctf to ctfinfo/Imagename.ctf:mrc

I am curious if I need to address some issues with my installations of Relion, gCTF, and Focus or is this intended behavior? The output for individual images during processing  (with gCTF) contains ".ctf:mrc", but not in the joined exported star file. Is that intentional? 

Thank you

**Comment by rdrighetto** [comment]
Dear Andrey,

Thanks for reporting this bug. I will fix them and let you know when it's done.

**Comment by rdrighetto** [comment]
The bugs should be fixed now. Please feel free to reopen this issue if you still encounter these problems with micrographs_all_defocus.star.
