### ISSUE TITLE
gCTF script not creating log file

### ISSUE THREAD

**Issue by hansenbry** [C-CINA/focus#233]
When running gCTF (on average) I get the below error message on all my data.  The ctf correction appears to have been done, but the ctfres value can't be populated.  Any ideas on what I need to fix?

Processing done successfully.
Average defocus = 1.976 microns
CTF Figure of Merrit: 0.181696
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'movie_aligned_Sum_EPA.log'
############################process_ctf finished.#############################
Traceback (most recent call last): 
File "/opt/rml/focus/scripts/proc/gctfres.py", line 11, in 
epa = np.loadtxt( epa_file, skiprows=1 ).astype( 'float32' ) 
File "/home/hansenbry/EMAN2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 734, in loadtxt

**Comment by hansenbry** [comment]
Just checking in to see if there are any updates to this issue?

**Comment by rdrighetto** [comment]
Hi Bryan,

I was not able to reproduce this issue, which has been previously reported (see #206) . Most likely it's a Gctf version-related bug. We are using Gctf v1.06 with CUDA v8.0. Please also make sure you use the latest FOCUS release from our website.
