### ISSUE TITLE
CMakeLists.txt don't respect cmake DESTDIR relocations when creating qt.conf.

### ISSUE THREAD

**Issue by andrew-niaid** [C-CINA/focus#234]
The CMakeLists.txt file for several apps/ don't respect cmake DESTDIR relocations when creating qt.conf.

[gist patch to fix](https://gist.github.com/andrew-niaid/0039274307626c99b0cb209ff4342809)

**Comment by rdrighetto** [comment]
The patch was applied. Thanks for contributing!
