### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by alexander-a-mestre** [C-CINA/focus#235]
Dear Focus-Team, 

Our group is trying to use Focus to process 2D crystals.  Currently, we are struggling to run the program “import movie from digitial micrograph”. Each time we attempt to import the movie we get the error message that there are too many arguments.  

We have our Project directory set up as follows:
- Project_Directory/raw/movie01

We imported the raw gain-corrected mrc movies into Focus. 

After selecting the movie from the library we to run the "Import Movie from Digitial Micrograph" program.   

Our values are as follows
Image Number: 0000000001
Comment: - 
Magnification: 40159.674
Pixel Size: 5
Calculate Pixel Size From magnification: yes
Pixel Size on Sample Level: 1.24503
Use Pixel Size on header: yes
Original Pixel Size on Sample Level: 1.24503
Crop Histogram: yes
Crop_histogram_stdev:4 
Original Filename: -

Name of rawstack: movie01.mrc
Original name of raw stack: Project_Directory/raw/movie01.mrc
Name of gain corrected raw stack: raw_gaincorrectedstack 
SerialEM applied conversion Factor:1
SerialEM default conversion factor: 12

Binning of this image before motioncor2: 2= bin by a factor of 2
Binning target pixel size: 1

Source of information about frame dose: 1= use electron counts in image
Manually defined frame image dose: .
Factor to increase the automatically determined electron dose: 1.3
Frame Image dose: ScriptWillPutNumberHere
Frame Sample Dose: ScriptWillPutNumberHere
Total Sample Dose: ScriptWillPutNumberHere
CS:2
HT voltage: 300

How do we troubleshoot the “too many arguments” error message?

Best, 
Alex

**Comment by alexander-a-mestre** [comment]
Hi Sorry for the delayed reply. 

The project directory had the test gain corrected movie in it. 


The error message is shown below:

##################################import_DM###################################
 
############################################
# Parameters requested by the Script       #
############################################
tempkeep = n
imagename = 5cisp020movie
nonmaskimagename = ScriptWillPutNameHere
crop_histogram = y
crop_histogram_stdev = 4.0
movie_stackname = 5cisp020movie
import_rawstack = 5cisp020movie.mrc
import_rawstack_type = 1
import_gainref = 
import_gainref_original = 
import_defects = 
import_defects_original = 
raw_gaincorrectedstack = 5cisp020movie
magnification = 40159.674
stepdigitizer = 5.0
calc_from_sample_pixel = y
sample_pixel = 1.24503
take_header_orig_sample_pixel = y
orig_sample_pixel = 1.24503
movie_imagenumber_total = 
import_bin = 2
import_bin_target = 1.000
import_rawstack_original = /exports/people/ungerlab/aam1730/thirdattemptatfocus/5cisp020movie.mrcs
serialem_factor = 1
serialem_default_factor = 12
import_original_time = 1537915383000
frame_image_dose_source = 1
frame_image_dose_factor = 1.3
frame_image_dose_manually = .
movie_image_dose_source = 0
movie_image_dose_factor = 1.3
movie_image_dose_manually = 80.0
cs = 2
kv = 300.0
defocus_phase_shift_doit = -
thread_number = 12
export_basedir = ../../EXPORT
export_rawstack_subdir = raw
 
############################################
# Parameters from the Preferences settings #
############################################
app_python = /usr/bin/python
app_cadaver = /usr/bin/cadaver
app_anaconda = /usr/bin/python
dir_ccp4 = /opt/ccp4-7.0-x64
app_gawk = /usr/bin/gawk
cuda_library = /usr/local/cuda/lib64
app_unblur = /usr/local/cina/unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe
app_motioncor2 = /opt/motioncor2/x64/MotionCor2
app_gctf = /usr/local/cina/Gctf/0.50_cuda7.5/bin/gctf
app_ctffind = /usr/local/cina/ctffind/ctffind-4.1.4/ctffind
app_gautomatch = /opt/gautomatch/x64/Gautomatch_v0.56/bin/gautomatch
dir_eman2 = /opt/eman2/2.12/x64/EMAN2
dir_imod = /opt/imod/x64/imod_4.9.9
dir_frealign = /opt/frealign/frealign_v9.11
dir_relion = /usr/local/relion
Default_CS = 2
Default_KV = 300.0
Default_phase_shift_doit = n
status_folder_update = n
status_folder = none
status_microscope = Titan
status_refresh_rate = 0
status_webdav = http://my.server.com/files
website_blur_doit = y
website_blurkernel = 7
SCRATCH_DISK = .
FAST_DISK = .
GPU_how_many = 1
GPU_to_use = 0
GPU_cycle = n
MotionCor2_alone = y
 
#############################################
# Now the remainder of the original script: #
#############################################
 
++++++++++++++++++++++++++++++++
Initializing script environment
++++++++++++++++++++++++++++++++
date = Wed Oct 3 15:55:17 CDT 2018
system = Linux
bin_2dx = /exports/Linux/opt/focus-git/x64/focus-20180925-1/kernel/mrc/bin
proc_2dx = /exports/Linux/opt/focus-git/x64/focus-20180925-1/scripts/proc
==== dir_eman2 = /opt/eman2/2.12/x64/EMAN2 ============================================================================================================================================================
==== app_python = /usr/bin/python =====================================================================================================================================================================
==== app_anaconda = /usr/bin/python ===================================================================================================================================================================
==== dir_frealign = /opt/frealign/frealign_v9.11 ======================================================================================================================================================
==== dir_relion = /usr/local/relion ===================================================================================================================================================================
Raw movie as gain-corrected stack is present as MRCS file.
Gain-corrected stack is 5cisp020movie.mrcs
 Image has size 3710, which is small enough, no binning done.
<error>source: Too many arguments.
</error>::#############################import_DM finished.##############################

**Comment by alexander-a-mestre** [comment]
Any advice you have would be greatly appreciated.

**Comment by rdrighetto** [comment]
Hi,

Sorry for the delay. This happens because in your system csh is not tcsh. In modern Linux distros csh is just a symlink to tcsh. For more details and solution, please refer to our issue #171 

Hope this helps.
