### ISSUE TITLE
File movie_aligned.mrcs from MotionCor2 is not removed

### ISSUE THREAD

**Issue by PaulVanSchayck** [C-CINA/focus#236]
I ran into the issue where our project directory got very big. When inspecting it turned out that the files movie_aligned.mrcs was kept (even after running export and clean up script). This is, I presume, the aligned movie stack. 

Inspecting a bit further I think MotionCor2 1.1.0 always creates this file and assumes it to be overwritten as a temporary file. It seems none of the focus scripts removes this file.

To workaround this problem I made this change to the cleanup scripts:

https://github.com/M4I-nanoscopy/focus/commit/f6d7d0e511383a38d138834fd173523a8cf38d2a

**Comment by rdrighetto** [comment]
Hi Paul,

Thanks a lot for your contribution. This was intentional because sometimes people wanted to export the aligned stacks (rarely needed in practice though). I have added the option to delete this file (enabled by default) to the cleanup script.
