### ISSUE TITLE
full-screen display of non-square images shows image with wrong dimensions.

### ISSUE THREAD

**Issue by sthennin** [C-CINA/focus#98]
If creating a final map with SPIDER of, e.g., 6x6 unit cells in p6 symmetry, then the final map has dimensions of 3408x1968 pixels. However, it is displayed as 3408x1140 pixels, so much to low in height. This is a 2dx_image display problem, because the same MRC format file displays correctly in Chimera.

**Comment by sthennin** [comment]
CCP4 or SPIDER SCRIPT bug.  Better eliminate both.
this is in "Generate Map", when producing more than one normal "2x2 unit cell" final map.

**Comment by sthennin** [comment]
spider is now completely removed. CCP4 is still used.

**Comment by nikhilbiyani** [comment]
Fixed now.
